name: 'build-test'
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
      - name: Get Chrome version
        id: chrome-version
        run: echo "version=(Get-Item (Get-Command chrome).Source).VersionInfo.ProductVersion" >> $GITHUB_OUTPUT
      - run: echo "Chrome version ${{ steps.chrome-version.outputs.version }}"