on:
  push:
    tags:
      - '*'

name: Create Release And Upload assets

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 'stable'
      - name: Chrome version
        run: |
          echo ${{ steps.setup-chrome.outputs.chrome-version }}
      - name: Compress Chrome
        run: |
          7z a -tzip chrome-win.zip 'C:\Program Files\Google\Chrome'
      - name: Download Driver
        run: |
          $build_version=${{ steps.setup-chrome.outputs.chrome-version }}.Split('.')[0]
          $release_version=Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$build_version | Select -ExpandProperty Content
          Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/$release_version/chromedriver_win32.zip -OutFile chromedriver_win32.zip
      - name: Release Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.setup-chrome.outputs.chrome-version }}
          files: |
            chrome-win.zip
            chromedriver_win32.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}